apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: interview-buddy
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cornflowerblu/interview-buddy
  ref:
    branch: main
